# stage 환경
---
spring:
  config:
    activate:
      on-profile: stage
  data:
    mongodb:
      uri: mongodb://open.jinotech.com:32017
      database:
logging:
  file:
    name: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
